[build]
builder = "nixpacks"
buildCommand = "npm install && cd backend && npm install && cd ../frontend && npm install && npm run build:prod"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.regions]
"singapore" = 1
